version: "3.1"
   
services:
  db:
    image: postgres:latest
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    image: backend:0.1
    command: bash -c "
      while !</dev/tcp/db/5432; do sleep 1; done;
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
     "
    volumes:
      - ./backend:/code
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=password
    ports:
      - "8000:8000"
    depends_on:
      - db
