version: "3.1"
   
services:
  db:
    image: postgres:latest
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  
  web:
    image: adeiarias/as_project_backend:development
    command: bash -c "
      while !</dev/tcp/db/5432; do sleep 1; done;
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
     "
    volumes:
      - ./backend:/code
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=password
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  frontend:
    image: adeiarias/as_project_frontend:development
    volumes:
      - ./frontend:/frontend_code
    ports:
      - "1080:1080"
    depends_on:
      - db
      - web
