apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  # Crearemos solamente una replica, no necesitamos más
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      # Especificaciones del contenedor
      containers:
        - name: django
          # Qué imagen usar para la base de datos
          image: adeiarias/client_django_as:latest
          # Qué comando se ejecutarán al iniciar el contenedor
          command: ["/bin/sh", "-c"]
          args:
            - ./wait-for-it.sh postgres-service:5432 --timeout=300 -- python manage.py makemigrations;
              python manage.py migrate;
              python manage.py runserver 0.0.0.0:8000;
          # Especificar los puertos
          ports:
            - containerPort: 8000
          # Especificar las variables de entorno
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: DB_HOST
              value: postgres-service
