kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    app: django-container
  # Especificar los puertos
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  # Usaremos loadbalancer, porque queremos acceder desde el exterior
  type: LoadBalancer
