kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  # Capacidad que tendrá el volumen
  capacity:
    storage: 2Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  # Cual será la ruta en la cual se guardarán todos los archivos
  hostPath:
    path: /data/postgres-pv
