# Generated by Django 3.2.4 on 2021-11-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211103_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='user_id',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='message',
            field=models.TextField(default='0000000'),
        ),
        migrations.AlterModelTable(
            name='data',
            table='info',
        ),
    ]
