kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  # 2Gi de almacenamiento
  resources:
    requests:
      storage: 2Gi
